# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-16 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('titulo', models.CharField(max_length=300)),
                ('texto', models.TextField(default='empieza a escribir, no lo pienses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('SON', 'Soneto'), ('TER', 'Terceto'), ('CUA', 'Cuarteto'), ('LIR', 'Lira')], max_length=3)),
            ],
        ),
    ]
