# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poema',
            name='tags',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
