# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-16 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemas', '0002_poema_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='poema',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
