# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-16 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemas', '0003_poema_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poema',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
