# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-17 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poemas', '0004_auto_20190116_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='poema',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poema',
            name='visibility',
            field=models.CharField(choices=[('PUB', 'P\xfablica'), ('PRI', 'Privada')], default='PUB', max_length=3),
        ),
    ]
